### ISSUE TITLE
Branch names for preview deploys

### ISSUE THREAD

**Issue by emarx** [chalk-ai/roadmap#13]
Today, `chalk apply --no-promote` gives back a unique deployment id for each new deploy. As a data scientist, if you want to test out a  new feature or resolver, you need to keep copying that deployment id into a Jupyter notebook to test your new feature. It would be more helpful to target a deployment branch, and re-request the data after the deploy completes.

**Comment by rileysiebel** [comment]
Implemented via branch deployment, a new development paradigm with many advantages.  More to, come, stay tuned! https://docs.chalk.ai/docs/changelog#branch-deployments
