### ISSUE TITLE
Faster `chalk apply` (< 30s)

### ISSUE THREAD

**Issue by emarx** [chalk-ai/roadmap#2]
Today, running `chalk apply --await` takes about 2 minutes and 30 seconds. When you haven't changed your `requirements.txt` or `Dockerfile`, `chalk apply` should be fast! Our target for this issue is to move the time down to less than 30 seconds.

**Comment by rileysiebel** [comment]
Chalk apply performance is dramatically improved with branch deployments and faster core deployments.
https://docs.chalk.ai/docs/changelog#speed-improvements-for-deployments
https://docs.chalk.ai/docs/changelog#branch-deployments
