### ISSUE TITLE
Faster `chalk apply` (< 15s)

### ISSUE THREAD

**Issue by emarx** [chalk-ai/roadmap#5]
By the end of Q3, we want to reduce `chalk apply --await` from 2 minutes and 30 seconds to 30 seconds. But that's still too slow! When you haven't changed your requirements.txt or Dockerfile, chalk apply should be blazingly fast! Our target for this issue is to move the time down to less than 15 seconds.

**Comment by rileysiebel** [comment]
Branch deployments take <30 seconds.  Regular deployments have also been improved, reducing time to deploy by around 2 minutes when dependencies haven't changed since the last deployment

**Comment by rileysiebel** [comment]
https://docs.chalk.ai/docs/changelog#speed-improvements-for-deployments
https://docs.chalk.ai/docs/changelog#speed-improvements-for-deployments
